apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: {{ .Values.app.name }}-techdocs
  namespace: {{ .Values.app.namespace }}   
spec:
  description: This Task can be used to a generate TechDocs
  params:
  - name: docs-path
    type: string
  - name: entity
    type: string
  - name: s3-env-secret-name
    default: "s3-env"
    type: string
  - name: current-namespace 
    default: "default"
    type: string

  steps:
  - name: generate-techdocs
    image: image-registry.openshift-image-registry.svc:5000/$(params.current-namespace)/{{ .Values.image.name }}:{{ .Values.image.tag }}
    script: |
      echo generate-techdocs
      pwd
      mkdir /tmp/out
      ls -l       
      ~/techdocs-cli generate  --no-docker --source-dir $(params.docs-path) --output-dir /tmp/out
      echo publish-techdocs 
      ~/techdocs-cli publish --directory /tmp/out --publisher-type awsS3 --storage-name  $S3_BUCKET --awsEndpoint $S3_URL --awsS3ForcePathStyle --entity $(params.entity)
    env:
      - name: AWS_REGION
        valueFrom:
          secretKeyRef:
            name: $(params.s3-env-secret-name)
            key: "AWS_REGION"
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: $(params.s3-env-secret-name)
            key: "AWS_ACCESS_KEY_ID"
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: $(params.s3-env-secret-name)
            key: "AWS_SECRET_ACCESS_KEY"
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: $(params.s3-env-secret-name)
            key: "AWS_SECRET_ACCESS_KEY"
      - name: S3_URL
        valueFrom:
          secretKeyRef:
            name: $(params.s3-env-secret-name)
            key: "S3_URL"
      - name: S3_BUCKET
        valueFrom:
          secretKeyRef:
            name: $(params.s3-env-secret-name)
            key: "S3_BUCKET"
      - name: NODE_TLS_REJECT_UNAUTHORIZED
        valueFrom:
          secretKeyRef:
            name: $(params.s3-env-secret-name)
            key: "NODE_TLS_REJECT_UNAUTHORIZED"          
    workingDir: $(workspaces.workspace.path)

  workspaces:
  - description: The workspace for the docs code.
    name: workspace